### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by iluuu1994** [iluuu1994/php-src#24]
## Methods only

* `+` Less nesting
* `+` Simple syntax
* `+` Familiar syntax for JS/Python users
* `+` Likely the least complex
* `-` No way to declare auto-generated properties, useful for BC
* `-` Can't be used in CPP
* `-` Additional keyword with a BC break
    - A new keyword would also be required for lazy and guard
* `-` Additional checks for compatibility checks for getter/setter types and signature in general
* `-` It's not immediately evident this declares a property

```php
class Foo {
    public get bar(): string {}
    public set bar(string $value) {}
}
```

## Property referencing the methods

* `+` Less nesting
* `+` Works nicely with CPP
* `+` No custom parent call syntax is necessary, just `parent::{get,set}Bar()`
* `-` Even more checks for compatibility checks with the property itself
* `-` Method can be called directly at least in private scope
* `-` Confusion with visibility of accessor vs method
* `-` Methods have to be explicitly named, even though they're only referenced once

```php
class Foo {
    public string $bar { get getBar; set setBar; }
    private function getBar(): string {}
    private function setBar(string $value) {}
}
```

## C# style syntax

* `+` Shortest syntax
* `+` Inferred, consistent types in accessors
* `+` Familiar syntax for C#/Swift users (arguably much more used there than in JS/Python)
* `+` Accessors are visually grouped together
* `+` Simpler compatibility checks
* `-` More nesting
* `-` Only works well for auto-generated accessors in CPP, unless support is added for short accessors (`get => $this->_foo;`) which might lead to bike-shedding
  * `-` For `=>`, double method call if combined with another method for mimicking the "Property referencing the methods" syntax

```php
class Foo {
    public string $bar { get {} set {} }
}
```

**Comment by Crell** [comment]
Methods only:

> It's not immediately evident this declares a property 

It wouldn't in this approach. It also wouldn't have `lazy` or `guard`, realistically.  Going method-only would mean we're just doing externalizing the `switch` part of `__get`.  Whether that's good or bad is debatable, but by design this approach would have fewer moving parts.

Basically, these two become synonymous:

```php
class Foo
{
  private array $vars = [];
  public function __get(string $var) {
    switch ($var) {
      case 'beep': return $this->vars['beep']; break;
    }
  }

  public get beep(): string {
    return $this->vars['beep'];
  }
}
```

**Comment by Crell** [comment]
>  Methods have to be explicitly named, even though their only referenced once

s/their/they're/

**Comment by iluuu1994** [comment]
> but by design this approach would have fewer moving parts.

That's certainly true. Although it doesn't solve the [uniform access principle](https://en.wikipedia.org/wiki/Uniform_access_principle) part of the problem. That problem doesn't exist for JavaScript. I'm not sure about Python but I'm guessing the same.
